### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by tristanjodsalz** [Minecrafter5K/World-of-Fossils#11]
- [ ] Suchleiste
- [x] location feld auf upload seite
- [x] Login seite stylen 
- [x] acounts reparieren
- [x] wenn kein bild oder 3d modell vorhanden ist soll auch nichts angezeigt werden
